### ISSUE TITLE
Suggestion: Enter the service directly into JOSM maps for easier access

### ISSUE THREAD

**Issue by stoecker** [hfs/brandenburg-addresses#2]
At the page
https://josm.openstreetmap.de/wiki/Maps/Germany
you can add service like this, so users don't need to manually add them.

See
https://josm.openstreetmap.de/wiki/Maps
for description.

It seems the original address for BB layer could also be added?

**Comment by hfs** [comment]
Thanks for the suggestion! I’ve finally added the layer here: https://josm.openstreetmap.de/wiki/Maps/Germany?action=diff&version=353&old_version=352
